# This workflow will build a Java project with Gradle
# This file was contributed by ysenih@erpya.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish Project

on:
  release:
    types:
      - created

jobs:

  # Build dist application adempiere
  build-app:
    name: Build dist adempiere-zk
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 11
          architecture: x64
      
      - name: Set Main Version
        run: echo "MAIN_VERSION=${{ github.event.release.name }}" >> client/src/main/java/org/adempiere/version.properties
      
      - name: Set Release Date
        run: echo "DATE_VERSION=$(date +'%Y-%m-%d')" >> client/src/main/java/org/adempiere/version.properties
      
      - name: Set Implementation Version
        run: echo "IMPLEMENTATION_VERSION=${{ github.event.release.tag_name }}" >> client/src/main/java/org/adempiere/version.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.2
          arguments: clean refreshDependences releaseZK
        env:
          ORG_GRADLE_PROJECT_deployUsername: ${{ secrets.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_deployToken: ${{ secrets.DEPLOY_TOKEN }}
          GITHUB_DEPLOY_REPOSITORY: ${{ secrets.DEPLOY_REPOSITORY }}

      - name: Upload dist app zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: adempiere-shw-zk.war
          path: build/release/adempiere-shw-zk.war

  # Publish Binaries
  # publish-binaries:
  #   name: Upload Binaries adempiere-zk
  #   needs: build-app
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: Download build war app
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: adempiere-shw-zk.war

  #     - name: Upload zip
  #       uses: skx/github-action-publish-binaries@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         args: adempiere-shw-zk.war
  
  # Docker Build 
  build-publish-docker:
    name: Build and Publish Docker Images
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Download build war app
        uses: actions/download-artifact@v4
        with:
          name: adempiere-shw-zk.war
                
      #Prepare for Build Docker Image
      - name: Prepare build
        run: |
          mkdir -p docker/jetty/zk-ui/
          cp adempiere-shw-zk.war docker/jetty/zk-ui/zk-ui.war
          unzip -j adempiere-shw-zk.war -d docker/jetty/zk-ui/lib WEB-INF/lib/*.jar

      # install the doctl on the runner
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push image in Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/jetty/Dockerfile
          platforms: linux/amd64,linux/amd64/v2,linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.DOCKER_REPO_ADEMPIERE_ZK }}:jetty-${{ github.event.release.tag_name }}
            ${{ secrets.DOCKER_REPO_ADEMPIERE_ZK }}:jetty
      
